verbose: true
message-sender: true
norepeat: true
similarration: 90
norepeatmaxdelay: 15
# Example: "2 5f gg 8b 33 hj 6zb 6573" has 8 words and 6 words with numbers
max-words-with-numbers: 5
max-separated-numbers: 3
max-word-length: 20
banned-text:
  - "http"
  - "https"
  - "://"
  - ".org"
  - ".com"
  - ".net"
  - ".org"
  - ".co"
  - ".cc"
  - ".tk"
  - ".ga"
  - ".gg"
  - ".io"
backend-processing:
  enable: false
  strategy: "before" # before / after / exclusive
  allow-on-error: true
  timeout: 1000
  retries: 1
  servers: # load balanced with round-robin
    - http://localhost:25501