verbose: true
message-sender: true
no-repeat: true
# How many times after sending a message should the bot wait before sending the same message again
no-repeat-time: 60
# How many messages are stored that are now allowed to be repeated?
no-repeat-stack-size: 5
# How similar from 1-100 are two messages allowed to be before they are considered the same?
no-repeat-similar-ratio: 90
# How many of the last message of a user are allowed to have a number inside them?
no-repeat-number-messages: 5
no-repeat-number-amount: 3
# Store last global messages and compare them for no repeat as well
global-repeat-check: true
# Store the last x amount of global messages to compare for no repeat
global-message-stack-size: 40
# Example: "2 5f gg 8b 33 hj 6zb 6573" has 8 words and 6 words with numbers
max-words-with-numbers: 5
max-separated-numbers: 3
max-word-length: 20
banned-text-partial-ratio: 40
banned-text:
  - "http"
  - "https"
  - "://"
  - ".org"
  - ".com"
  - ".net"
  - ".org"
  - ".co"
  - ".cc"
  - ".tk"
  - ".ga"
  - ".gg"
  - ".io"
