verbose: true
message-sender: true
norepeat: true
similarration: 90
norepeatmaxdelay: 15
banned-text:
  - "http"
  - "https"
  - "://"
  - ".org"
  - ".com"
  - ".net"
  - ".org"
  - ".co"
  - ".cc"
  - ".tk"
  - ".ga"