name: PistonFilter
version: ${project.version}
main: net.pistonmaster.pistonfilter.PistonFilter
description: Chat filter addon for PistonChat.
depend: [ "PistonChat" ]
commands:
  pistonfilter:
    description: Main command for PistonFilter
    permission: pistonfilter.admin
permissions:
  pistonfilter.admin:
    description: Admin permission for PistonFilter
    default: op
    children:
      pistonfilter.bypass: true
  pistonfilter.bypass:
    description: Permission to bypass the chatfilter