name: PistonFilter
version: ${project.version}
main: net.pistonmaster.pistonfilter.PistonFilter
description: Chat filter companion for PistonChat.
depend: [ "PistonChat" ]
commands:
  pistonfilter:
    description: Main command for PistonFilter